-- Schema for the PasswordArchive database on PostgreSQL.
--
-- Unlike the TimeReporting schema, this one is not owned by EF Core migrations: the
-- archive belongs to the separate security application, and this project only reads
-- from it. The statements below match the mappings in
-- GMG.TimeReporting.Core/PasswordArchiveData/PasswordArchiveContext.cs, so running
-- them produces a database the API can talk to.
--
-- Identifiers are quoted because the entities keep their PascalCase names.

CREATE TABLE "SystemUsers" (
    "SystemUserId"         integer GENERATED BY DEFAULT AS IDENTITY,
    "SystemUsername"       character varying(50) NOT NULL,
    "HashedSystemPassword" character(64)         NOT NULL,
    "DefaultUsername"      character varying(50),
    "SystemPasswordHint"   character varying(50),
    CONSTRAINT "PK_SystemUsers" PRIMARY KEY ("SystemUserId")
);

CREATE TABLE "Categories" (
    "CategoryId"   integer GENERATED BY DEFAULT AS IDENTITY,
    "CategoryName" character varying(50) NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("CategoryId")
);

CREATE TABLE "Passwords" (
    "PasswordId"       integer GENERATED BY DEFAULT AS IDENTITY,
    "SystemUserId"     integer               NOT NULL,
    "Title"            character varying(50) NOT NULL,
    "Password"         character varying(50) NOT NULL,
    "URL"              character varying(50),
    "Username"         character varying(50),
    "Notes"            text,
    "ExpirationDate"   timestamp without time zone,
    "CreatedDate"      timestamp without time zone NOT NULL,
    "LastModifiedDate" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Passwords" PRIMARY KEY ("PasswordId"),
    CONSTRAINT "FK_Passwords_SystemUsers" FOREIGN KEY ("SystemUserId")
        REFERENCES "SystemUsers" ("SystemUserId") ON DELETE CASCADE
);

CREATE TABLE "PasswordCategories" (
    "PasswordId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    CONSTRAINT "PK_PasswordCategories" PRIMARY KEY ("PasswordId", "CategoryId"),
    CONSTRAINT "FK_PasswordCategories_Passwords" FOREIGN KEY ("PasswordId")
        REFERENCES "Passwords" ("PasswordId") ON DELETE CASCADE,
    CONSTRAINT "FK_PasswordCategories_Categories" FOREIGN KEY ("CategoryId")
        REFERENCES "Categories" ("CategoryId") ON DELETE CASCADE
);

CREATE INDEX "IX_Passwords_SystemUserId" ON "Passwords" ("SystemUserId");
CREATE INDEX "IX_PasswordCategories_CategoryId" ON "PasswordCategories" ("CategoryId");
