// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace GMG.TimeReporting.Core.TimeReportingData
{
    public partial class TimeEntry
    {
        public int TimeEntryId { get; set; }
        public string Title { get; set; } = null!;
        public DateTime StartTime { get; set; }
        public DateTime? EndTime { get; set; }
    }
}
